const piknik = [
    {
        name            :   'Achem' ,
        age             :   22 ,
        fee             :   1500 ,
        tokenNumber     :   102 ,
        loocation       :   'Dhaka' ,
        time            :   '9.00 AM' ,
    },
    {
        name            :   'Rayhan' ,
        age             :   32 ,
        fee             :   1500 ,
        tokenNumber     :   102 ,
        loocation       :   'Khulna' ,
        time            :   '9.00 AM' ,
    },
    {
        name            :   'Akash' ,
        age             :   23 ,
        fee             :   500 ,
        tokenNumber     :   102 ,
        loocation       :   'Rajshahi' ,
        time            :   '9.00 AM' ,
    },
    {
        name            :   'Shakil' ,
        age             :   41 ,
        fee             :   1000 ,
        tokenNumber     :   102 ,
        loocation       :   'Kurigram' ,
        time            :   '9.00 AM' ,
    },
    {
        name            :   'Rabbi' ,
        age             :   23 ,
        fee             :   1500 ,
        tokenNumber     :   102 ,
        loocation       :   'Japan' ,
        time            :   '9.00 AM' ,
    },
    {
        name            :   'Takla Murad' ,
        age             :   32 ,
        fee             :   500 ,
        tokenNumber     :   102 ,
        loocation       :   'USA' ,
        time            :   '9.00 AM' ,
    },
    {
        name            :   'Nur Amin' ,
        age             :   24 ,
        fee             :   500 ,
        tokenNumber     :   102 ,
        loocation       :   'CTG' ,
        time            :   '9.00 AM' ,
    },
]